version: '3.8'

services:
  web:
    build:
      context: .
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: passwordsavoir
      POSTGRES_DB: espace-savoir

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: passwordsavoir
      POSTGRES_DB: espace-savoir
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
